<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ListAuctions.wsdl"/>
      <rootElement name="AuctionCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ListAuctions"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/wsdl/abstractAuction.wsdl"/>
      <rootElement name="Auctions" namespace="http://xmlns.qualogy.com/marQtplaats"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [SUN NOV 10 11:28:48 CET 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xqcm="http://xmlns.qualogy.com/marQtplaats"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ListAuctions"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns0="urn:abstractAuction"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Marqtplaats/AuctionService/ListAuctions"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top plt wsdl xsd tns xqcm soap12 soap mime ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <xqcm:Auctions>
      <xsl:for-each select="/top:AuctionCollection/top:Auction">
        <xsl:if test=".">
          <xqcm:Auction>
            <xqcm:Description>
              <xsl:value-of select="top:description"/>
            </xqcm:Description>
            <xsl:if test="top:startingPrice">
              <xqcm:StartingPrice>
                <xsl:value-of select="top:startingPrice"/>
              </xqcm:StartingPrice>
            </xsl:if>
            <xqcm:MinimumIncrement>
              <xsl:value-of select="top:minIncrement"/>
            </xqcm:MinimumIncrement>
            <xsl:if test="top:informPrice">
              <xqcm:InformPrice>
                <xsl:value-of select="top:informPrice"/>
              </xqcm:InformPrice>
            </xsl:if>
            <xqcm:AuctionStatus>
              <xsl:value-of select="top:status"/>
            </xqcm:AuctionStatus>
            <xqcm:StartDate>
              <xsl:value-of select="top:startdate"/>
            </xqcm:StartDate>
            <xqcm:EndDate>
              <xsl:value-of select="top:enddate"/>
            </xqcm:EndDate>
            <xqcm:Seller>
              <xsl:value-of select="top:seller"/>
            </xqcm:Seller>
            <xqcm:ID>
              <xsl:value-of select="top:id"/>
            </xqcm:ID>
          </xqcm:Auction>
        </xsl:if>
      </xsl:for-each>
    </xqcm:Auctions>
  </xsl:template>
</xsl:stylesheet>
