<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://services.qualogy.com/validationService/1.0"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://services.qualogy.com/validationService/1.0"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ValidationBPEL">
        <plnk:role name="validateEmail" portType="tns:validateEmail"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://services.qualogy.com/validationService/1.0" location="oramds:/apps/wsdl/abstractValidationService.wsdl"/>
</wsdl:definitions>
