<?binding.jca ParticipantIsSeller_db.jca?>
<wsdl:definitions name="ParticipantIsSeller" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Marqtplaats/ParticipantService/ParticipantIsSeller" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Marqtplaats/ParticipantService/ParticipantIsSeller" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ParticipantIsSeller">
    <plt:partnerLinkType name="ParticipantIsSeller_plt">
        <plt:role name="ParticipantIsSeller_role">
            <plt:portType name="tns:ParticipantIsSeller_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ParticipantIsSeller" schemaLocation="xsd/ParticipantIsSeller_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:ParticipantsPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="ParticipantsCollection_msg">
        <wsdl:part name="ParticipantsCollection" element="top:ParticipantsCollection"/>
    </wsdl:message>
    <wsdl:portType name="ParticipantIsSeller_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:ParticipantsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
